
name: Backup Mastodon Account
on:
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Backup Mastodon Account
        uses: ./
        id: backup
        with:
          server: tech.lgbt
        env:
          ACCESS_TOKEN: "${{ secrets.ACCESS_TOKEN }}"